"""create parts table

Revision ID: 514afdf54327
Revises: 91b5f26be34e
Create Date: 2026-07-01 23:40:59.685932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '514afdf54327'
down_revision: Union[str, Sequence[str], None] = '91b5f26be34e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('brand', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('engine_code', sa.String(), nullable=False),
    sa.Column('price_usd', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('parts')
    # ### end Alembic commands ###
